s = set()

n1 = int(input("Enter number "))
s.add(int(n1))
n1 = int(input("Enter number "))
s.add(int(n1))
n1 = int(input("Enter number "))
s.add(int(n1))
n1 = int(input("Enter number "))
s.add(int(n1))
n1 = int(input("Enter number "))
s.add(int(n1))
n1 = int(input("Enter number "))
s.add(int(n1))
n1 = int(input("Enter number "))
s.add(int(n1))
n1 = int(input("Enter number "))
s.add(int(n1))

print(s)
print(sum(s))